config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  get "posts/random", to: "posts#random", as: :random
  get "/profile", to: "users#edit", as: :profile
  get "posts/all", to: "posts#all", as: :all
  resources :users
  resources :posts do
    resources :votes, shallow: true, only: [:create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  # Create a better looking URL for logging in
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true, default_url: "/assets/thumb/missing_avatar.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
private

  # Make the current_user method available to views, not just controllers!
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, except: [:index, :show, :random]


  def index
    @posts = Post.left_joins(:votes).group(:id).order('COUNT(votes.id) DESC')
  end

  def show
    @post = Post.find(params[:id])
    @hash = Gmaps4rails.build_markers(@post) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
    end
  end

  def new
    @post = Post.new
    @posts = Post.all
    @hash = Gmaps4rails.build_markers(@posts) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
    end
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to root_path
    else
      flash[:notice] = "Error Post not created!"
    end
  end

  def random
    post = Post.all.sample
    redirect_to post_path(post)
  end

  def profile
  end

  def all
    @posts = current_user.posts.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to all_path, notice: "Post was successfully destroyed."
  end


  private
    # Implement Strong Params
    def post_params
      params.require(:post).permit(:image,:description,:latitude, :longitude)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # Nothing to do here other than render new.html.erb
  end

  def create
    # Not using an instance variable since
    # we're not providing the user to a view
    user = User.find_by(email: params[:email])
    # Taking advantage of the && logical operator's
    # short-circuiting
    if user && user.authenticate(params[:password])
      # Successful log in!
      session[:user_id] = user.id
      # notice: is a special flash[:notice] accessor
      redirect_to root_path, notice: 'Logged in!'
    else
      # flash.now is used for messaging
      # during the CURRENT request
      flash.now.alert = 'Invalid login credentials - try again!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
  end

  def new
    # Provide the model instance to the form_for helper
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path, notice: "Account was successfully destroyed."
  end

  private

    # Implement Strong Params
    def user_params
      params.require(:user).permit(:first_name,:last_name, :email, :password, :password_confirmation, :image)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :authorize

  def create
    post = Post.find(params[:post_id])
    post.votes.create(user: current_user) unless Vote.find_by(user: current_user, post: post)
    redirect_back(fallback_location: root_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodchella</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyADO8b-4bSRJh40x8T_Q_kG5baHUgZydHM" async defer></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" async defer></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript' async defer></script> <!-- only if you need custom infoboxes -->

    <%= favicon_link_tag %>
 </head>

  <body>
  	<nav class="navbar custom-nav navbar-inverse navbar-fixed-top">
          <a class="navbar-brand" href="/">Foodchella</a>
        </div>
        <%if !current_user %>
  			<ul class="nav navbar-nav navbar-right">
  	      <li class="navbar-right"><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
  	      <li class="navbar-right"><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
        <%else%>
          <div class="nav navbar-nav navbar-right dropdown zero">
             <span style="color:#9d9d9d;"><%= current_user.email%></span> <a href="/profile" class="zero"><%= image_tag current_user.image, height: 50,class: "avatar" %></a>
            <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown" style="background-color:black;">
             <i class="glyphicon glyphicon-menu-hamburger" style="color:white;"></i>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="/profile"><span class="glyphicon glyphicon-user"></span> My Profile</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="/posts/all"><span class="glyphicon glyphicon-edit"></span> My Posts</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="/posts/new"><span class="glyphicon glyphicon-pencil"></span> New Post</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="/posts/random"><span class="glyphicon glyphicon-random"></span> Random Post</a></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="https://oppakimchee.github.io/project1/"><span class="glyphicon glyphicon-usd"></span> Black Jack!</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="http://leejb91.github.io/project1/"><span class="glyphicon glyphicon-info-sign"></span> Jerry's Mancala</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="http://ajalmaguer.github.io/wheel-of-fortune/" ><span class="glyphicon glyphicon-info-sign"></span> AJ's Wheel of Fortune</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><span class="glyphicon glyphicon-music"></span><audio src="bgm.mp3" controls loop></audio></a></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation"><%= link_to raw("<span class='glyphicon glyphicon-log-out'></span> Log Out"), session_path("dummy"), method: :delete%></li>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |post| %>
  <% if @post.errors.any? %>
    <div class="error_messages text-center">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @post.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field text-center" id="sizing-addon1">
    <%= post.label :description %>
    <%= post.text_field :description, class: "form-control"%>
  <div class="actions text-center" style="margin: 10px auto">
    <%= submit_tag "Update!",class: 'btn btn-success'%>
    <%= @post.id ? raw("<a class='btn btn-warning' id='editCancel'>Cancel</a>") : "" %> <br><br>
    <%= link_to 'Delete Post', @post, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } if current_user %>
  </div>
<% end %>

app/views/posts/all.html.erb
<h1 class="text-center">My Posts</h1>
<ul class="text-center">
	<div class="container">
		<% @posts.each_slice(3) do |post| %>
			<div class="row">
				<% post.each do |post| %>
				<div class="col-md-4">
					<div class="col-xs-12">
						<%= link_to post_path(post), class: "image-container" do%>
							<%= image_tag post.image.url, class: "img-hover" %>
						  <div class="middle">
						  	"<%= post.description %>"<br>
						  	Posted by: <%= post.user.email %> <br>
							<span class='glyphicon glyphicon-heart'></span><%= post.votes.count %> <br>
							Posted on <%= post.created_at.strftime("%B %d, %Y @ %I:%M:%S %p") %>
						  </div>
						<% end %>
					</div>
				</div>
				<%end%>
			</div>
		<% end %>
	</div>
</ul>

app/views/posts/index.html.erb
<% unless current_user %>
<div class="subscribe-me" style="background-color:rgba(34,34,34,.9);height: 340px;color:#9d9d9d;">
    <a href="#close" class="sb-close-btn">x</a>
    <h3 style="text-align:center; margin: 0 auto;">Log In!</h3>
    <%= form_tag sessions_path do %>
      <div class="field text-center">
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email] %>
      </div>
      <div class="field text-center">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div><br>
      <div class="actions text-center"><%= submit_tag "Log In",class: 'btn btn-info'%></div>
       <h5 class="text-center">Don't have an account? <a href="/users/new">Sign up here!</a></h5>
    <% end %>
</div>
<% end %>
<h1 class="text-center">Top Posts</h1><br><br>
<p class="text-center" id="notice"><strong><%= notice %></strong></p><br>
<ul class="text-center">
	<div class="container">
		<% @posts.each_slice(3) do |post| %>
			<div class="row">
				<% post.each do |post| %>
				<div class="col-md-4">
					<div class="col-xs-12">
						<%= link_to post_path(post), class: "image-container" do%>
							<%= image_tag post.image.url, class: "img-hover" %> <br><br><br><br>
						  <div class="middle">
						  	"<%= post.description %>"<br>
						  	Posted by: <%= post.user.email %> <br>
							<span class='glyphicon glyphicon-heart'></span><%= post.votes.count %> <br>
							Posted on <%= post.created_at.strftime("%B %d, %Y @ %I:%M:%S %p") %>
						  </div>
						<% end %>
					</div>
				</div>
				<%end%>
			</div>
		<% end %>
	</div>
</ul>

<script>
	$(".subscribe-me").subscribeBetter({
	  trigger: "onload",       // You can choose which kind of trigger you want for the subscription modal to appear. Available triggers are "atendpage" which will display when the user scrolls to the bottom of the page, "onload" which will display once the page is loaded, and "onidle" which will display after you've scrolled.
	  animation: "fade",          // You can set the entrance animation here. Available options are "fade", "flyInRight", "flyInLeft", "flyInUp", and "flyInDown". The default value is "fade".
	  delay: 0,                   // You can set the delay between the trigger and the appearance of the modal window. This works on all triggers. The value should be in milliseconds. The default value is 0.
	  showOnce: true,             // Toggle this to false if you hate your users. :)
	  autoClose: false,           // Toggle this to true to automatically close the modal window when the user continue to scroll to make it less intrusive. The default value is false.
	  scrollableModal: false      //  If the modal window is long and you need the ability for the form to be scrollable, toggle this to true. The default value is false.
	});
</script>

app/views/posts/new.html.erb
<h1 class="text-center">New Posts</h1><br>
<p class="text-center" id="notice"><strong><%= notice %></strong></p>
<%= form_for @post, url: posts_path, html: { multipart: true } do |post| %>
  <% if @post.errors.any? %>
    <div class="error_messages text-center">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @post.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= post.hidden_field :latitude %>
  <%= post.hidden_field :longitude %>
  <div class="field text-center">
    <%= post.label :image %>
    <img id="img_prev" src="#" alt="upload image preview" style="display: none;"> <br>
    <%= post.file_field :image, class: "m-center", onchange: "readURL(this);"%>
  </div><br>
  <div class="field text-center">
    <%= post.label :description %>
    <%= post.text_field :description,placeholder: "ex. name of food, restraunt, location etc...",size: 60%>
    <div class="actions text-center" style="margin-top:10px;"><%= post.submit 'Post', class: 'btn btn-info', disabled: !current_user %></div>
    <div class="text-center" style="width: 250px; margin: 10px auto;">
      <div class="text-center" id="geolocation" style='width: 250px; height: 250px;'></div>
    </div>
  </div>
<% end %>

<script>

  $('form').on('submit', function() {
    $('#post_longitude').attr('value', lng);
    $('#post_latitude').attr('value', lat);
  });
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'geolocation'} }, function(){
    // be aware chrome >= 50 requires https for geolocation to work
    if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(displayOnMap);
  });

  var lat, lng;

  function displayOnMap(position){
    lat = position.coords.latitude;
    lng = position.coords.longitude;
    var marker = handler.addMarker({
      lat: position.coords.latitude,
      lng: position.coords.longitude
    });
    handler.map.centerOn(marker);
  };

  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .show()
          .attr('src', e.target.result)
          .width(250)
          .height(250);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/posts/show.html.erb
<div class="container" id="show">
	<div class="col-sm-5">
		<div class="image-container">
			<h1><%= @post.description %></h1>
				<%= image_tag @post.image.url %>
			<span class="pull-left">Posted by: <%= @post.user.email %></span>
			<span class="pull-right"><%= link_to raw("<span class='glyphicon glyphicon-thumbs-up'></span>"), post_votes_path(@post), method: :post %> <span class='glyphicon glyphicon-heart'></span><%= @post.votes.count %></span><br>
			Posted on <%= @post.created_at.strftime("%B %d, %Y @ %I:%M:%S %p") %>
		</div>
		<% if current_user && @post.user.id == current_user.id %>
			<button id="editButton" class="btn btn-warning" style="display: block; margin: 0 auto;">edit</button>
			<div id="editForm" style="display: none;">
			  <%= render "form" %> <br>
			</div>
		<% end %>
	</div>
	<div style="width: 250px; margin: 10px auto;">
	 	<div class="text-center" id="map" style='width: 250px; height: 250px; margin: 0 auto;'></div>
	</div>
</div>
<script>
	    $("#editButton").on("click",function(){
	    console.log('edit')
	    $("#editForm").show()
	    $("#editButton").hide()

	  })
	  $("#editCancel").click(function(){
	    console.log('cancel')
	    $("#editForm").hide()
	    $("#editButton").show()
	  })

	handler = Gmaps.build('Google');
	handler.buildMap({
	  provider: {
	    disableDefaultUI: true
	    // pass in other Google Maps API options here
	  },
	 	internal: {
	    id: 'map'
	  	}
	},
		function(){
			markers = handler.addMarkers(<%=raw @hash.to_json %>);
			handler.bounds.extendWith(markers);
			handler.fitMapToBounds();
			handler.getMap().setZoom(16);
		}
	);
</script>

app/views/users/_form.html.erb
<%= form_for @user do |user| %>
  <% if @user.errors.any? %>
    <div class="error_messages text-center">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field text-center">
    <%= user.label :first_name %>
    <%= user.text_field :first_name %>
  </div><br>
  <div class="field text-center">
    <%= user.label :last_name %>
    <%= user.text_field :last_name %>
  </div><br>
  <div class="field text-center">
    <%= user.label :email_or_username %>
    <%= user.text_field :email %>
  </div><br>
  <div class="field text-center">
    <%= user.label :password %>
    <%= user.password_field :password %>
  </div><br>
  <div class="field text-center">
    <%= user.label :password_confirmation %>
    <%= user.password_field :password_confirmation %>
  </div><br>
  <div class="field text-center">
    <%= user.label :profile_picture, class: "l-center" %>
    <img id="img_prev" src="#" alt="upload image preview" style="display: none;"> <br>
    <%= user.file_field :image, class: "m-center",onchange: "readURL(this);"%>
  </div><br>
  <div class="actions text-center">
    <%= submit_tag "Update!",class: 'btn btn-success'%>
    <%= @user.id ? raw("<a class='btn btn-warning' id='editCancel'>Cancel</a>") : "" %> <br><br>
    <%= link_to 'Delete Account', current_user, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure? All posts created will also be deleted.' } if current_user %>
  </div>
<% end %>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .show()
          .attr('src', e.target.result)
          .width(250)
          .height(250);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/users/edit.html.erb
<div class="text-center"><%= image_tag current_user.image, class: "ava text-center", height: 100%></div>
<h1 class="text-center"><%= current_user.email%></h1>
<div id="infoForm">
  <div class="text-center">
    First Name: <%= @user.first_name %> <br>
    Last Name: <%= @user.last_name %> <br>
    Email or Username: <%= @user.email %> <br>
    <button id="editButton" class="btn btn-warning">edit</button>
  </div>
</div>

<br>
<hr>
<br>


<div id="editForm" style="display: none;">
  <%= render "form" %> <br>
</div>

<script>
    $("#editButton").on("click",function(){
    console.log('edit')
    $("#editForm").show()
    $("#infoForm").hide()

  })
  $("#editCancel").click(function(){
    console.log('cancel')
    $("#editForm").hide()
    $("#infoForm").show()
  })

  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .show()
          .attr('src', e.target.result)
          .width(250)
          .height(250);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }

</script>

app/views/users/new.html.erb
<h1 class="text-center">Sign Up</h1>
<%= form_for @user, url: users_path, html: { multipart: true } do |user| %>
  <% if @user.errors.any? %>
    <div class="error_messages text-center">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field text-center">
    <%= user.label :first_name %>
    <%= user.text_field :first_name %>
  </div>
  <div class="field text-center">
    <%= user.label :last_name %>
    <%= user.text_field :last_name %>
  </div>
  <div class="field text-center">
    <%= user.label :email_or_username %>
    <%= user.text_field :email %>
  </div>
  <div class="field text-center">
    <%= user.label :password %>
    <%= user.password_field :password %>
  </div>
  <div class="field text-center">
    <%= user.label :password_confirmation %>
    <%= user.password_field :password_confirmation %>
  </div><br>
  <div class="field text-center">
    <%= user.label :profile_picture, class: "l-center" %>
    <img id="img_prev" src="#" alt="upload image preview" style="display: none;"> <br>
    <%= user.file_field :image, class: "m-center",onchange: "readURL(this);"%>
  </div><br>
  <div class="actions text-center"><%= submit_tag "Sign Up!",class: 'btn btn-info'%></div>
  <h5 class="text-center">already have an account? <a href="/login">log in here!</a></h5>
<% end %>

<script>

  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .show()
          .attr('src', e.target.result)
          .width(250)
          .height(250);
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>